name = "portal"
main = "worker/index.js"
compatibility_date = "2026-07-31"
workers_dev = false

[[d1_databases]]
binding = "ACTS_DB"
database_name = "portal-db"
database_id = "9b095e00-ad71-46c9-a33f-e9f67000e104"
migrations_dir = "database/migrations"

[[r2_buckets]]
binding = "ACTS_MEDIA"
bucket_name = "acts-midias"

[[r2_buckets]]
binding = "ACTS_DATA"
bucket_name = "acts-dados"

[[queues.producers]]
binding = "ACTS_QUEUE"
queue = "acts-queues"

[env.development]
name = "portal-development"

[[env.development.d1_databases]]
binding = "ACTS_DB"
database_name = "portal-db"
database_id = "9b095e00-ad71-46c9-a33f-e9f67000e104"
migrations_dir = "database/migrations"

[[env.development.r2_buckets]]
binding = "ACTS_MEDIA"
bucket_name = "acts-midias"

[[env.development.r2_buckets]]
binding = "ACTS_DATA"
bucket_name = "acts-dados"

[[env.development.queues.producers]]
binding = "ACTS_QUEUE"
queue = "acts-queues"

[env.staging]
name = "portal-staging"

[[env.staging.d1_databases]]
binding = "ACTS_DB"
database_name = "portal-db"
database_id = "9b095e00-ad71-46c9-a33f-e9f67000e104"
migrations_dir = "database/migrations"

[[env.staging.r2_buckets]]
binding = "ACTS_MEDIA"
bucket_name = "acts-midias"

[[env.staging.r2_buckets]]
binding = "ACTS_DATA"
bucket_name = "acts-dados"

[[env.staging.queues.producers]]
binding = "ACTS_QUEUE"
queue = "acts-queues"

[env.production]
name = "portal"

[[env.production.d1_databases]]
binding = "ACTS_DB"
database_name = "portal-db"
database_id = "9b095e00-ad71-46c9-a33f-e9f67000e104"
migrations_dir = "database/migrations"

[[env.production.r2_buckets]]
binding = "ACTS_MEDIA"
bucket_name = "acts-midias"

[[env.production.r2_buckets]]
binding = "ACTS_DATA"
bucket_name = "acts-dados"

[[env.production.queues.producers]]
binding = "ACTS_QUEUE"
queue = "acts-queues"
