import test from'node:test';import assert from'node:assert/strict';import {MemoryPrivateStorage}from'../src/storage.js';import {changePlan,changeProtected,decide,findOrCreate,loadClient,publicSummary,requireAdmin,submitRegistration,updateContact}from'../src/clientes.js';
const env={SESSION_SECRET:'session-secret',CPF_INDEX_SECRET:'cpf-secret',SUPERADMIN_GOOGLE_SUBS:'admin'};const req=new Request('https://app.test',{headers:{'user-agent':'test'}});
async function setup(sub='client'){const storage=new MemoryPrivateStorage();const c=await findOrCreate(storage,{googleSub:sub,gmail:`${sub}@gmail.com`},env,req,new Date('2026-01-01'));return{storage,session:{clienteId:c.operational.clienteId,googleSub:sub,role:sub==='admin'?'SUPERADMIN':'CLIENTE'},client:c}}
const payload=(revision=1,cpf='52998224725')=>({revision,nomeCivil:'Pessoa Teste',cpf,dataNascimento:'1990-02-10',nacionalidade:'brasileira',sexoCadastral:'feminino',telefone:'43999990000',whatsapp:'43999990000',telefoneWhatsapp:true,endereco:{cep:'86000000',pais:'Brasil',estado:'Paraná',municipio:'Londrina',rua:'Rua Teste',numero:'10',bairro:'Centro',complemento:''},tipoDocumento:'RG',aceites:{maioridade:true,veracidade:true,termos:true,privacidade:true,tratamentoDados:true,publicacaoFutura:true,versaoTermos:'2',versaoPrivacidade:'2'}});
test('cadastro completo abre rascunho aguardando análise e esconde CPF do resumo',async()=>{const x=await setup();const result=await submitRegistration(x.storage,x.session,payload(),env,req,new Date('2026-01-01'));assert.equal(result.states.cadastro,'aguardando_analise');assert.equal(result.states.anuncio,'rascunho');assert.equal(result.states.site,'nao_publicado');assert.equal(result.states.portal,'nao_listado');assert.doesNotMatch(JSON.stringify(publicSummary(await loadClient(x.storage,x.session.clienteId))),/52998224725|dataNascimento/)});
test('CPF duplicado é reservado por HMAC',async()=>{const storage=new MemoryPrivateStorage();const a=await findOrCreate(storage,{googleSub:'a',gmail:'a@gmail.com'},env,req);const b=await findOrCreate(storage,{googleSub:'b',gmail:'b@gmail.com'},env,req);await submitRegistration(storage,{clienteId:a.operational.clienteId,googleSub:'a',role:'CLIENTE'},payload(),env,req);await assert.rejects(()=>submitRegistration(storage,{clienteId:b.operational.clienteId,googleSub:'b',role:'CLIENTE'},payload(),env,req),e=>e.code==='REVISION_CONFLICT')});
test('campos desconhecidos, menor e revisão concorrente são recusados',async()=>{let x=await setup();await assert.rejects(()=>submitRegistration(x.storage,x.session,{...payload(),extra:true},env,req),e=>e.code==='UNKNOWN_FIELD');x=await setup();await assert.rejects(()=>submitRegistration(x.storage,x.session,{...payload(),dataNascimento:'2012-01-01'},env,req,new Date('2026-01-01')),e=>e.code==='MINOR_NOT_ALLOWED');x=await setup();await assert.rejects(()=>submitRegistration(x.storage,x.session,payload(9),env,req),e=>e.code==='REVISION_CONFLICT')});
test('cliente só atualiza contato/endereço e não acessa SUPERADMIN',async()=>{const x=await setup();assert.throws(()=>requireAdmin(x.session),e=>e.code==='SUPERADMIN_REQUIRED');await submitRegistration(x.storage,x.session,payload(),env,req);await assert.rejects(()=>updateContact(x.storage,x.session,{...payload(2),nomeCivil:'Novo'}),e=>e.code==='UNKNOWN_FIELD')});
test('SUPERADMIN corrige protegido somente com motivo e mantém auditoria',async()=>{const x=await setup();await submitRegistration(x.storage,x.session,payload(),env,req);const admin={googleSub:'admin',role:'SUPERADMIN'};await assert.rejects(()=>changeProtected(x.storage,admin,x.session.clienteId,{revision:1,motivo:'',changes:{nomeCivil:'Novo'}}));const changed=await changeProtected(x.storage,admin,x.session.clienteId,{revision:1,motivo:'Documento conferido',changes:{nomeCivil:'Nome Corrigido'}});assert.equal(changed.revision,2);const audit=await x.storage.list(`clientes/${x.session.clienteId}/auditoria/`);assert.ok(audit.length>=3)});
test('decisões, suspensão, bloqueio, reativação e plano manual',async()=>{const x=await setup();await submitRegistration(x.storage,x.session,payload(),env,req);const admin={googleSub:'admin',role:'SUPERADMIN'};let rev=2;for(const state of ['aprovado','correcao_solicitada','reprovado','suspenso','bloqueado','reativado']){const op=await decide(x.storage,admin,x.session.clienteId,{revision:rev++,decisao:state,motivo:'Análise humana'});assert.equal(op.states.cadastro,state==='reativado'?'aprovado':state)}const op=await changePlan(x.storage,admin,x.session.clienteId,{revision:rev,id:'inicial',status:'ativo',inicio:'2026-01-01',vencimento:'2026-02-01',limites:{status:'pendente'},motivo:'Ativação manual'});assert.equal(op.plan.status,'ativo');assert.equal(op.plan.historico.length,1)});
