import test from 'node:test';import assert from 'node:assert/strict';import {MemoryPrivateStorage}from'../src/storage.js';import {projectPublic,buildShards,normalizeSlug,publishClient,flags}from'../src/publicacao.js';import {processAges,processBirthdays,processPlans,reconcile,auditPublic,executarCron}from'../src/cron.js';import {cacheControlFor}from'../src/cache.js';
const now=new Date('2026-09-05T15:00:00Z');
function fixture(){return {client:{operational:{clienteId:'cli_1',diretorio:'mulheres',states:{cadastro:'aprovado',identidade:'aprovada',documentos:'aprovados',conta:'ativa'},plan:{id:'inicial',status:'cortesia'},contato:{whatsapp:'5543999999999'}},identity:{dataNascimento:'2000-09-05',nomeCivil:'Privado'}},draft:{perfil:{estado:'validado',nomeArtistico:'Ágata',apresentacao:'Uma apresentação pública suficientemente completa.',cidadePrincipal:'londrina',cidadesAtendimento:['londrina'],categorias:[],bairroPublico:'Centro'},site:{estado:'validado',titulo:'Ágata'}},media:{itens:[{id:'001',tipo:'foto',status:'aprovada',arquivo:'midias/clientes/cli_1/fotos/001.webp',miniatura:'midias/clientes/cli_1/fotos/001-thumb.webp'}]}}}
test('projeção aplica allowlist, calcula idade e nunca publica nascimento/PII',()=>{const p=projectPublic({...fixture(),now,publicationId:'p1'});assert.equal(p.profile.idade,26);assert.equal(p.profile.slug,'agata');assert.doesNotMatch(JSON.stringify(p),/dataNascimento|nomeCivil|cpf|googleSub|gmail/)});
test('inelegibilidade cobre menor, plano, mídia, diretório, cidade, categoria e obrigatório',()=>{for(const mutate of [x=>x.client.identity.dataNascimento='2010-01-01',x=>x.client.operational.plan.status='vencido',x=>x.media.itens[0].status='rejeitada',x=>x.client.operational.diretorio='outro',x=>x.draft.perfil.cidadePrincipal='outra',x=>x.draft.perfil.categorias=['inventada'],x=>delete x.draft.perfil.nomeArtistico]){const x=fixture();mutate(x);assert.throws(()=>projectPublic({...x,now,publicationId:'p'}),/PUBLICATION_INELIGIBLE/)}});
test('slug normaliza, bloqueia reservado e shards são determinísticos, isolados e limitados',async()=>{assert.equal(normalizeSlug(' Ana Júlia '),'ana-julia');assert.throws(()=>normalizeSlug('public'));const cards=Array.from({length:5},(_,i)=>({clienteId:`c${i}`,slug:`s${5-i}`,diretorio:'mulheres'}));const a=await buildShards(cards,{publicationId:'p',target:2,maxBytes:9999,cidade:'londrina',diretorio:'mulheres'}),b=await buildShards(cards.reverse(),{publicationId:'p',target:2,maxBytes:9999,cidade:'londrina',diretorio:'mulheres'});assert.equal(a.shards.length,3);assert.deepEqual(a,b);assert.ok(a.manifest.hash);assert.ok(a.shards.every(s=>s.anuncios.every(x=>x.diretorio==='mulheres')))});
test('flags desligam por padrão e falha não troca ponteiro; publicação é idempotente',async()=>{assert.deepEqual(flags({}),{publication:false,writes:false,cron:false,publicV2:false});const priv=new MemoryPrivateStorage(),pub=new MemoryPrivateStorage();await assert.rejects(publishClient(priv,pub,'x',{},{}),/PUBLICATION_DISABLED/);assert.equal(await pub.get('dados/sistema/versao.json'),null)});
test('idade/aniversário anual e planos pendentes são privados e idempotentes',async()=>{const s=new MemoryPrivateStorage(),f=fixture(),clients=[{...f.client,draft:f.draft,consentWhatsapp:true}];let ages=await processAges(s,clients,now);assert.equal(ages[0].idade,26);assert.equal((await processAges(s,clients,now)).length,0);assert.equal((await processBirthdays(s,clients,now)).length,1);assert.equal((await processBirthdays(s,clients,now)).length,0);const plansOut=await processPlans(s,clients,now);assert.equal(plansOut[0].acaoAutomatica,false);assert.ok(plansOut[0].pendenciaAdministrativa)});
test('reconciliação usa lote/checkpoint/retomada e auditoria detecta privado e diretório misto',async()=>{const s=new MemoryPrivateStorage();for(let i=0;i<3;i++)await s.put(`sistema/operacional/clientes/${i}.json`,{});let seen=[];assert.equal((await reconcile(s,k=>seen.push(k),{batchSize:2})).processed,2);assert.equal((await reconcile(s,k=>seen.push(k),{batchSize:2})).processed,1);const p=new MemoryPrivateStorage();await p.put('vazou.json',{cpf:'1'});await p.put('shards/a.json',{diretorio:'mulheres',anuncios:[{diretorio:'homens'}]});assert.deepEqual((await auditPublic(p)).map(x=>x.type).sort(),['MIXED_DIRECTORY','PRIVATE_DATA']);assert.deepEqual(await executarCron({},{}),{enabled:false,processed:0})});
test('cache separa assets, ponteiros e privado',()=>{assert.match(cacheControlFor('/app/site/a.js'),/immutable/);assert.match(cacheControlFor('/dados/sistema/versao.json'),/must-revalidate/);assert.equal(cacheControlFor('/api/painel'), 'no-store')});
