export const painelJs = String.raw`
const loading=document.querySelector('#loading'),loginView=document.querySelector('#login'),privateView=document.querySelector('#private'),loginForm=document.querySelector('#login-form'),profileForm=document.querySelector('#profile-form'),loginMessage=document.querySelector('#login-message'),profileMessage=document.querySelector('#profile-message'),save=document.querySelector('#save');
const fields=['displayName','bio','phone','website','instagram','whatsapp'];
const messages={400:'Confira os dados informados.',401:'Email ou senha inválidos.',403:'Esta ação não está disponível.',404:'Perfil não encontrado.',500:'Não foi possível concluir agora. Tente novamente.'};
function message(node,text,type='error'){node.textContent=text;node.className='message '+type}
function loggedOut(text=''){privateView.hidden=true;loginView.hidden=false;loading.hidden=true;profileForm.reset();document.querySelector('#account-email').textContent='';document.querySelector('#plan-name').textContent='';loginForm.elements.password.value='';message(loginMessage,text)}
function render(data){loginView.hidden=true;loading.hidden=true;privateView.hidden=false;document.querySelector('#account-email').textContent=data.user?.email||'';const plan=String(data.plan||'STANDARD').toUpperCase();document.querySelector('#plan-name').textContent=plan;document.querySelector('#plan-detail').textContent=plan==='PREMIUM'?'Minisite habilitado':'Minisite não incluído';for(const name of fields)profileForm.elements[name].value=data.profile?.[name]??'';message(profileMessage,'','')}
async function json(path,options){const response=await fetch(path,{credentials:'same-origin',...options});let data={};try{data=await response.json()}catch{}return{response,data}}
async function loadMe(){loading.hidden=false;try{const{response,data}=await json('/api/me');if(response.status===401)return loggedOut();if(!response.ok)throw Object.assign(new Error(),{status:response.status});render(data)}catch(error){loading.hidden=true;loggedOut(messages[error.status]||'Não foi possível carregar o painel.') }}
loginForm.addEventListener('submit',async event=>{event.preventDefault();const button=loginForm.querySelector('button');button.disabled=true;message(loginMessage,'Entrando…','');try{const{response}=await json('/api/auth/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:loginForm.elements.email.value.trim(),password:loginForm.elements.password.value})});loginForm.elements.password.value='';if(!response.ok)return message(loginMessage,messages[response.status]||'Não foi possível entrar.');await loadMe()}catch{message(loginMessage,'Não foi possível entrar.')}finally{button.disabled=false}});
profileForm.addEventListener('submit',async event=>{event.preventDefault();if(!profileForm.reportValidity())return;save.disabled=true;message(profileMessage,'Salvando…','');const payload=Object.fromEntries(fields.map(name=>[name,profileForm.elements[name].value.trim()]));try{const{response}=await json('/api/me/profile',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});if(response.status===401)return loggedOut('Sua sessão expirou. Entre novamente.');if(!response.ok)return message(profileMessage,messages[response.status]||'Não foi possível salvar.');await loadMe();message(profileMessage,'Perfil salvo com sucesso.','success')}catch{message(profileMessage,'Não foi possível salvar.')}finally{save.disabled=false}});
document.querySelector('#logout').addEventListener('click',async event=>{event.currentTarget.disabled=true;try{const{response}=await json('/api/auth/logout',{method:'POST'});if(!response.ok)return message(profileMessage,messages[response.status]||'Não foi possível sair.');loggedOut()}catch{message(profileMessage,'Não foi possível sair.')}finally{event.currentTarget.disabled=false}});
loadMe();
`;
