const $ = (selector) => document.querySelector(selector); let session; let summary;
const api = async (path, options = {}) => { const headers = { ...(options.body && !(options.body instanceof Blob) ? { 'content-type': 'application/json' } : {}), ...(session && options.method && options.method !== 'GET' ? { 'x-csrf-token': session.csrfToken } : {}), ...options.headers }; const response = await fetch(path, { ...options, headers, body: options.body && !(options.body instanceof Blob) ? JSON.stringify(options.body) : options.body }); const data = await response.json(); if (!response.ok) throw new Error(data.code); return data.data ?? data; };
async function boot(){const config=await api('/api/auth/google/config');try{session=await api('/api/auth/session');$('#login').hidden=true;$('#app').hidden=false;$('#logout').hidden=false;$('#role').textContent=session.role;$('#admin-tab').hidden=session.role!=='SUPERADMIN';await refresh()}catch{$('#google-status').textContent=config.status;$('#google-login').hidden=!config.configured}}
async function refresh(){summary=await api('/api/painel/resumo');const labels={cadastro:'Cadastro',identidade:'Identidade',documentos:'Documentos',anuncio:'Anúncio',site:'Site',portal:'Portal'};$('#status-grid').innerHTML=Object.entries(summary.states).filter(([key])=>labels[key]).map(([key,value])=>`<article class="status"><span>${labels[key]}</span><strong>${escape(value.replaceAll('_',' '))}</strong></article>`).join('');$('#plan').textContent=`${summary.plan.id} · ${summary.plan.status} · vencimento: ${summary.plan.vencimento||'não definido'}`;$('#pending').textContent=summary.pendencias.length?summary.pendencias.join(', '):'Nenhuma pendência informada.';await notices()}
document.querySelectorAll('[data-view]').forEach((button)=>button.addEventListener('click',async()=>{document.querySelectorAll('.view').forEach((view)=>view.hidden=true);$(`#${button.dataset.view}`).hidden=false;document.querySelectorAll('.tabs button').forEach((item)=>item.removeAttribute('aria-current'));button.setAttribute('aria-current','page');if(button.dataset.view==='cadastro')await form();if(button.dataset.view==='admin')await clients('')}));
async function form(){if($('#registration').children.length)return;const config=await fetch('./config/formulario-cadastro-privado.json').then((r)=>r.json());$('#registration').innerHTML=config.secoes.map((section)=>`<fieldset class="step"><legend><strong>${escape(section.titulo)}</strong></legend><div class="fields">${section.campos.map(field).join('')}</div></fieldset>`).join('')+'<div class="actions"><button type="submit">Enviar cadastro privado</button><p id="form-result" role="status"></p></div>';$('#registration').addEventListener('input',progress);$('#registration').addEventListener('submit',(event)=>{event.preventDefault();$('#form-result').textContent='Use a API autenticada para uploads e envio; seus dados nunca são publicados nesta rodada.'});progress()}
function field(f){const id=`field-${f.id}`;if(f.tipo==='checkbox')return `<div class="check"><input id="${id}" name="${f.id}" type="checkbox" ${f.obrigatorio?'required':''}><label for="${id}">${escape(f.rotulo)}</label></div>`;const type={data:'date',tel:'tel',cpf:'text','email-confirmado':'email','arquivo-imagem':'file'}[f.tipo]||'text';const opts=f.tipo==='selecao'?`<select id="${id}" name="${f.id}" ${f.obrigatorio?'required':''}><option value="">Selecione</option>${f.opcoes.map((o)=>`<option>${escape(o)}</option>`).join('')}</select>`:`<input id="${id}" name="${f.id}" type="${type}" ${type==='file'?'accept="image/jpeg,image/png,image/webp" capture="user"':''} ${f.obrigatorio?'required':''}>`;return `<div><label for="${id}">${escape(f.rotulo)}</label>${opts}<small>${escape(f.ajuda)}</small></div>`}
function progress(){const controls=[...$('#registration').querySelectorAll('input,select')];const complete=controls.filter((c)=>c.type==='checkbox'?c.checked:c.value).length;$('#progress').textContent=`${Math.round(complete/controls.length*100)}%`}
async function notices(){const data=await api('/api/painel/avisos');$('#notice-list').innerHTML=data.avisos.length?data.avisos.map((n)=>`<article class="notice"><strong>${escape(n.titulo)}</strong><p>${escape(n.mensagem)}</p><small>${n.lido?'Lido':'Não lido'}</small></article>`).join(''):'<p>Nenhum aviso.</p>'}
async function clients(q){const data=await api(`/api/superadmin/clientes?q=${encodeURIComponent(q)}`);$('#clients').innerHTML=data.map((c)=>`<article class="client"><strong>${escape(c.clienteId)}</strong><p>${escape(c.gmail)} · ${escape(c.states.cadastro)}</p></article>`).join('')||'<p>Nenhum cliente encontrado.</p>'}
$('#search').addEventListener('submit',(e)=>{e.preventDefault();clients($('#query').value)});$('#logout').addEventListener('click',async()=>{await api('/api/auth/logout',{method:'POST'});location.reload()});function escape(value){const d=document.createElement('div');d.textContent=String(value);return d.innerHTML}boot();
