const FORMATS = Object.freeze({ 'image/jpeg': { extension: 'jpg', type: 'image', signatures: [[0xff, 0xd8, 0xff]] }, 'image/png': { extension: 'png', type: 'image', signatures: [[0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]] }, 'image/webp': { extension: 'webp', type: 'image', signatures: [[0x52, 0x49, 0x46, 0x46]] }, 'application/pdf': { extension: 'pdf', type: 'document', signatures: [[0x25, 0x50, 0x44, 0x46]] }, 'video/mp4': { extension: 'mp4', type: 'video', signatures: [[0x00, 0x00, 0x00]] } });
export class UploadError extends Error { constructor(code, message = 'Upload failed') { super(message); this.name = 'UploadError'; this.code = code; } }
const safeName = (name) => typeof name === 'string' && name.length <= 240 && !/[\\/\u0000-\u001f]/.test(name) && name !== '.' && name !== '..';
const bytesOf = async (file) => file instanceof Uint8Array ? file : file instanceof ArrayBuffer ? new Uint8Array(file) : file?.arrayBuffer ? new Uint8Array(await file.arrayBuffer()) : null;
const matches = (bytes, format, mime) => format.signatures.some((signature) => signature.every((value, index) => bytes[index] === value)) && (mime !== 'image/webp' || String.fromCharCode(...bytes.slice(8, 12)) === 'WEBP') && (mime !== 'video/mp4' || String.fromCharCode(...bytes.slice(4, 8)) === 'ftyp');
async function digest(bytes, cryptoApi) { const value = await cryptoApi.subtle.digest('SHA-256', bytes); return [...new Uint8Array(value)].map((byte) => byte.toString(16).padStart(2, '0')).join(''); }
export function createUpload(options) {
  if (!options?.storage?.put || !options.storage.delete || !options?.events?.publish || typeof options.registerMedia !== 'function' || !options.crypto?.subtle || typeof options.crypto.randomUUID !== 'function') throw new TypeError('Invalid Upload dependencies');
  const { storage, events, logger, registerMedia, crypto: cryptoApi, clock = () => new Date(), id = () => cryptoApi.randomUUID(), maxBytes = 20 * 1024 * 1024 } = options; const completed = new Map();
  const emit = (name, uploadId, context = {}, payload = {}) => events.publish({ name, version: '1.0', source: 'Upload', id: `evt_${id()}`, occurredAt: clock().toISOString(), payload: { uploadId, ...payload }, metadata: context.correlationId ? { correlationId: context.correlationId } : {} });
  async function upload(input, context = {}) {
    if (!context.userId) throw new UploadError('UNAUTHENTICATED'); if (!safeName(input?.name)) throw new UploadError('INVALID_NAME'); const format = FORMATS[input.mimeType]; if (!format) throw new UploadError('UNSUPPORTED_TYPE');
    const bytes = await bytesOf(input.file); if (!bytes || !bytes.length || bytes.length > maxBytes) throw new UploadError(bytes?.length ? 'FILE_TOO_LARGE' : 'INVALID_FILE'); if (!matches(bytes, format, input.mimeType)) throw new UploadError('CONTENT_MISMATCH');
    const checksumSha256 = await digest(bytes, cryptoApi); const requestKey = input.idempotencyKey ? `${context.userId}:${input.idempotencyKey}` : null; if (requestKey && completed.has(requestKey)) return completed.get(requestKey);
    const uploadId = `upl_${id()}`; const key = `uploads/${format.type}/${cryptoApi.randomUUID()}.${format.extension}`; await emit('UploadStarted', uploadId, context, { mediaType: format.type });
    try {
      await storage.put(key, bytes, { contentType: input.mimeType, metadata: { ownerId: context.userId, checksumSha256 } });
      let media; try { media = await registerMedia({ ownerId: context.userId, listingId: input.listingId ?? null, r2Key: key, mediaType: format.type, mimeType: input.mimeType, byteSize: bytes.length, checksumSha256, width: input.width, height: input.height, altText: input.altText, sortOrder: input.sortOrder }, context); } catch (error) { await storage.delete(key); throw error; }
      const result = Object.freeze({ uploadId, media, checksumSha256, byteSize: bytes.length, mimeType: input.mimeType }); if (requestKey) completed.set(requestKey, result); logger.info('Upload completed', { operation: 'upload.store', status: 'completed', uploadId, byteSize: bytes.length, mimeType: input.mimeType }); await emit('UploadCompleted', uploadId, context, { mediaId: media.id, byteSize: bytes.length, mimeType: input.mimeType }); return result;
    } catch (error) { logger.error('Upload failed', { operation: 'upload.store', status: 'failed', uploadId }); await emit('UploadFailed', uploadId, context, { reason: 'technical_failure' }); if (error instanceof UploadError) throw error; throw new UploadError('TECHNICAL_FAILURE'); }
  }
  return Object.freeze({ upload, allowedTypes: Object.freeze(Object.keys(FORMATS)), maxBytes });
}
