const root=document.querySelector('#conteudo'),origin='https://public.acompanhantesex.com/';
document.querySelector('#menu').onclick=e=>{const nav=document.querySelector('#nav'),open=nav.hidden;nav.hidden=!open;e.currentTarget.setAttribute('aria-expanded',String(open));};
const esc=v=>{const e=document.createElement('span');e.textContent=String(v??'');return e.innerHTML;};
async function json(path){const r=await fetch(new URL(path,origin),{headers:{accept:'application/json'}});if(!r.ok)throw Error('JSON');return r.json();}
const dirs=[['mulheres','Mulheres'],['homens','Homens'],['transex','Transex']];
async function render(){try{const host=location.hostname,path=location.pathname.split('/').filter(Boolean);if(host.endsWith('.acompanhantesex.com')&&!['www','public','acompanhantesex'].includes(host.split('.')[0]))return subdomain(host.split('.')[0]);if(!path.length)return home();const [city,directory,category,slug]=path;document.body.dataset.directory=directory;if(slug)return profileByPath(city,directory,category,slug);return listing(city,directory,category);}catch{root.replaceChildren(document.querySelector('#error').content.cloneNode(true));}}
async function home(){const cities=await json('dados/sistema/cidades.json');root.innerHTML=`<section class="hero"><p class="eyebrow">PORTAL</p><h1>Encontre seu anúncio</h1><p>Escolha a cidade e o diretório. Carregaremos somente essa seleção.</p></section><form class="chooser"><label>Cidade<select name="cidade">${cities.cidades.map(c=>`<option value="${esc(c.id)}">${esc(c.nome)}</option>`).join('')}</select></label><label>Diretório<select name="diretorio">${dirs.map(d=>`<option value="${d[0]}">${d[1]}</option>`).join('')}</select></label><button class="primary">Ver anúncios</button></form>`;root.querySelector('form').onsubmit=e=>{e.preventDefault();const d=new FormData(e.currentTarget);location.href=`/${d.get('cidade')}/${d.get('diretorio')}`;};}
function tabs(city,current){return `<nav class="directory-tabs" aria-label="Diretórios">${dirs.map(([id,label])=>`<a href="/${city}/${id}" ${id===current?'aria-current="page"':''}>${label}</a>`).join('')}</nav><a class="button" href="/">Trocar cidade</a>`;}
async function listing(city,directory,category){if(!dirs.some(x=>x[0]===directory))throw Error();const base=`dados/cidades/${city}/${directory}/${category?`categorias/${category}`:'todos'}`,manifest=await json(`${base}/manifesto.json`),parts=await Promise.all(manifest.shards.map(s=>json(`${base}/${s.arquivo}`))),cards=parts.flatMap(s=>s.anuncios);root.innerHTML=`${tabs(city,directory)}<h1>Anúncios em ${esc(city)}</h1><form class="filters"><label>Categoria<select name="categoria"><option value="">Todas</option>${(manifest.categorias||[]).map(c=>`<option ${c===category?'selected':''} value="${esc(c)}">${esc(c)}</option>`).join('')}</select></label><button class="primary">Aplicar filtro</button></form><section class="cards" aria-live="polite">${cards.length?cards.map(card).join(''):'<p>Nenhum anúncio encontrado</p>'}</section>`;root.querySelector('.filters').onsubmit=e=>{e.preventDefault();saveState();const c=new FormData(e.currentTarget).get('categoria');location.href=`/${city}/${directory}${c?`/${c}`:''}`;};restoreState();}
function card(x){return `<article class="card"><a href="${esc(x.urlCanonica)}" onclick="sessionStorage.setItem('portal-scroll',String(scrollY))">${x.miniaturaPrincipal?`<img src="${esc(x.miniaturaPrincipal)}" width="320" height="400" loading="lazy" decoding="async" alt="Foto de ${esc(x.nomeArtistico)}">`:''}<div class="card-content"><h2>${esc(x.nomeArtistico)}, ${x.idade}</h2><p>${esc(x.bairroPublico||x.cidadePrincipal)}</p><p>${esc(x.resumo)}</p><div class="chips">${x.categorias.map(c=>`<span class="chip">${esc(c)}</span>`).join('')}</div></div></a></article>`;}
async function profileByPath(city,directory,category,slug){const index=await json(`dados/sistema/slugs/${encodeURIComponent(slug)}.json`);return profile(index.clienteId,index.urlCanonica);}
async function subdomain(slug){const index=await json(`dados/sistema/slugs/${encodeURIComponent(slug)}.json`);history.replaceState({alias:true},'',location.pathname);return profile(index.clienteId,index.urlCanonica);}
async function profile(id,canonical){const [p,s,m]=await Promise.all(['perfil','site','midias'].map(x=>json(`dados/clientes/${id}/${x}.json`)));document.body.dataset.directory=p.diretorio;document.querySelector('#canonical').href=`https://acompanhantesex.com${canonical}`;root.innerHTML=`<article class="profile"><p class="eyebrow">${esc(p.cidadePrincipal)} · ${esc(p.diretorio)}</p><h1>${esc(p.nomeArtistico)}, ${p.idade}</h1><p class="lead">${esc(p.apresentacao)}</p><div class="chips">${p.categorias.map(c=>`<span class="chip">${esc(c)}</span>`).join('')}</div><h2>Galeria</h2><section class="gallery">${m.itens.map(media).join('')}</section><h2>Disponibilidade</h2><p>${esc(JSON.stringify(p.disponibilidade))}</p>${p.contatoPublico?.consentimento?`<a class="button" rel="nofollow" href="tel:${esc(p.contatoPublico.numero)}">Entrar em contato</a>`:''}<button class="primary" id="share">Compartilhar</button></article>`;root.querySelector('#share').onclick=()=>navigator.share?.({title:s.titulo||p.nomeArtistico,url:`https://acompanhantesex.com${canonical}`});document.querySelectorAll('video,audio').forEach(el=>el.onplay=()=>document.querySelectorAll('video,audio').forEach(other=>{if(other!==el)other.pause();}));}
function media(x){if(x.tipo==='foto')return `<img src="${esc(x.arquivo)}" width="${x.largura||720}" height="${x.altura||900}" loading="lazy" decoding="async" alt="">`;if(x.tipo==='video')return `<video controls preload="none" poster="${esc(x.capa||'')}" src="${esc(x.arquivo)}"></video>`;return `<audio controls preload="none" src="${esc(x.arquivo)}"></audio>`;}
function saveState(){history.replaceState({scrollY,filters:location.search},'');sessionStorage.setItem(`portal:${location.pathname}`,JSON.stringify({scrollY}));}function restoreState(){const s=history.state||JSON.parse(sessionStorage.getItem(`portal:${location.pathname}`)||'null');if(s?.scrollY)requestAnimationFrame(()=>scrollTo(0,s.scrollY));}
addEventListener('pagehide',saveState);render();
