export const minisiteJs = String.raw`
const root=document.querySelector('#minisite');
const RESERVED=new Set(['www','api','admin','painel','dados','media']);
const slug=location.hostname.toLowerCase().replace(/\.$/,'').split('.')[0];
const valid=/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug)&&!RESERVED.has(slug);
const el=(tag,attrs={},children=[])=>{const node=document.createElement(tag);for(const[key,value]of Object.entries(attrs)){if(key==='text')node.textContent=String(value??'');else if(value!=null)node.setAttribute(key,String(value))}node.append(...children);return node};
const safeUrl=value=>{try{const url=new URL(String(value));return ['https:','tel:','mailto:'].includes(url.protocol)?url.href:null}catch{return null}};
const imageUrl=item=>safeUrl(typeof item==='object'?item?.url:item);
function showMissing(){document.title='Minisite não encontrado — ACTS';root.replaceChildren(el('section',{class:'not-found'},[el('div',{},[el('p',{class:'mini-kicker',text:'ACTS'}),el('h1',{text:'Minisite não encontrado'}),el('p',{text:'Este perfil não está disponível.'}),el('a',{class:'mini-action',href:'https://acompanhantesex.com',text:'Voltar ao portal'})])]))}
function render(profile){const name=String(profile.name||slug),city=profile.city?.name||'Brasil';document.title=name+' — Minisite ACTS';document.querySelector('meta[name="description"]')?.setAttribute('content','Perfil público de '+name+' em '+city+'.');document.querySelector('link[rel="canonical"]')?.setAttribute('href','https://'+slug+'.acompanhantesex.com/');const gallery=(profile.gallery||[]).map(imageUrl).filter(Boolean).map((src,index)=>el('img',{src,alt:'Foto '+(index+1)+' de '+name,loading:index?'lazy':'eager'}));const media=el('div',{class:'mini-gallery'},gallery.length?gallery:[el('div',{class:'mini-photo-fallback',role:'img','aria-label':'Fotos indisponíveis'},[el('span',{text:'ACTS'})])]);const copy=el('div',{class:'mini-copy'},[el('span',{class:'mini-kicker',text:'Perfil oficial · '+city}),el('h1',{text:name}),el('p',{text:profile.presentation||'Perfil oficial no portal ACTS.'})]);const chips=el('div',{class:'mini-chips'});[...(profile.categories||[]),...(profile.tags||[])].forEach(value=>chips.append(el('span',{class:'mini-chip',text:value})));if(chips.children.length)copy.append(chips);if(profile.services?.length)copy.append(el('h2',{text:'Serviços'}),el('ul',{class:'mini-services'},profile.services.map(value=>el('li',{text:value}))));const contacts=el('div',{class:'mini-actions'});for(const[name,value]of Object.entries(profile.contacts||{})){const href=safeUrl(name==='phone'||name==='whatsapp'?('tel:'+value):value);if(href)contacts.append(el('a',{class:'mini-action',href,rel:'noopener',text:name==='whatsapp'?'WhatsApp':name==='phone'?'Telefone':name}))}copy.append(contacts);root.replaceChildren(el('section',{class:'mini-hero mini-wrap'},[media,copy]));if(profile.bloggerFeedUrl)queueMicrotask(()=>loadBlogger(profile.bloggerFeedUrl))}
async function loadBlogger(value){const base=safeUrl(value);if(!base)return;try{const url=new URL('/feeds/posts/default?alt=json&max-results=8',base),response=await fetch(url,{headers:{accept:'application/json'}});if(!response.ok)throw new Error();const feed=await response.json(),entries=Array.isArray(feed.feed?.entry)?feed.feed.entry:[];if(!entries.length)return;const wrap=el('div',{class:'mini-wrap'},[el('span',{class:'mini-kicker',text:'Blogger'}),el('h2',{text:'Publicações'})]);for(const entry of entries){const href=safeUrl(entry.link?.find(item=>item.rel==='alternate')?.href);if(!href)continue;const title=String(entry.title?.$t||'Publicação'),date=entry.published?.$t&&!Number.isNaN(Date.parse(entry.published.$t))?new Date(entry.published.$t).toLocaleDateString('pt-BR'):'';wrap.append(el('article',{class:'mini-post'},[el('div',{},[el('p',{class:'mini-kicker',text:date}),el('h3',{text:title}),el('a',{href,rel:'noopener noreferrer',text:'Ver publicação original'})])]))}if(wrap.querySelector('.mini-post'))root.append(el('section',{class:'mini-blog'},[wrap]))}catch{/* O perfil já está renderizado; o Blogger é opcional e nunca usa proxy. */}}
if(!valid)showMissing();else fetch('https://dados.acompanhantesex.com/minisites/'+encodeURIComponent(slug)+'.json',{headers:{accept:'application/json'}}).then(response=>{if(!response.ok)throw new Error();return response.json()}).then(render).catch(showMissing);
`;
