import { auditar } from './auditoria.js';
import { hmac } from './storage.js';
import { calcularIdade, diretorioParaSexo, normalizarCpf, textoSeguro, validarCpf } from './validacao.js';
import { httpError } from './auth/session.js';
import { privatePaths } from './paths.js';

const INITIAL_STATES = Object.freeze({ conta: 'ativa', cadastro: 'cadastro_incompleto', identidade: 'nao_enviada', documentos: 'nao_enviados', anuncio: 'rascunho', site: 'nao_publicado', portal: 'nao_listado' });
const DECISIONS = new Set(['aprovado', 'correcao_solicitada', 'reprovado', 'suspenso', 'bloqueado', 'reativado']);
export async function findOrCreate(storage, identity, env, request, now = new Date()) { const linkKey = `sistema/google/${await hmac(identity.googleSub, env.SESSION_SECRET)}.json`; let link = await storage.get(linkKey); if (link) return loadClient(storage, link.clienteId); const clienteId = `cli_${crypto.randomUUID().replaceAll('-', '')}`; const timestamp = now.toISOString(); const operational = base(clienteId, timestamp, { states: { ...INITIAL_STATES }, role: adminSubs(env).has(identity.googleSub) ? 'SUPERADMIN' : 'CLIENTE', gmail: identity.gmail, googleSub: identity.googleSub, contato: {}, endereco: {}, plan: { id: 'inicial', status: 'aguardando_ativacao', inicio: null, vencimento: null, limites: { status: 'pendente' }, historico: [] }, consumption: {}, pendencias: [] }); await storage.put(linkKey, { clienteId }, { createOnly: true }); await storage.put(opKey(clienteId), operational, { createOnly: true }); await auditar(storage, { clienteId, acao: 'cadastro_criado', ator: identity.googleSub, papel: operational.role, revision: 1, metadados: requestMeta(request) }, now); return { operational, identity: null };
}
export async function loadClient(storage, clienteId) { const operational = await storage.get(opKey(clienteId)); if (!operational) throw httpError(404, 'CLIENT_NOT_FOUND'); return { operational, identity: await storage.get(idKey(clienteId)), manifest: await storage.get(docKey(clienteId)), notices: await storage.get(noticeKey(clienteId)) };
}
export async function submitRegistration(storage, session, body, env, request, now = new Date()) { exact(body, ['revision', 'nomeCivil', 'cpf', 'dataNascimento', 'nacionalidade', 'sexoCadastral', 'telefone', 'whatsapp', 'telefoneWhatsapp', 'endereco', 'tipoDocumento', 'aceites']); const current = await loadClient(storage, session.clienteId); checkRevision(current.operational, body.revision); if (current.identity) throw httpError(403, 'PROTECTED_DATA_LOCKED'); const cpf = normalizarCpf(body.cpf); if (!validarCpf(cpf)) throw httpError(422, 'CPF_INVALID'); const age = calcularIdade(body.dataNascimento, now); if (age < 18) throw httpError(422, 'MINOR_NOT_ALLOWED'); const directory = diretorioParaSexo(body.sexoCadastral); validateAddress(body.endereco); validateAcceptances(body.aceites); const cpfHash = await hmac(cpf, env.CPF_INDEX_SECRET); await storage.put(`sistema/cpf/${cpfHash}.json`, { clienteId: session.clienteId }, { createOnly: true }); const timestamp = now.toISOString(); const identity = base(session.clienteId, timestamp, { nomeCivil: textoSeguro(body.nomeCivil, 160), cpf, dataNascimento: body.dataNascimento, nacionalidade: textoSeguro(body.nacionalidade, 80), sexoCadastral: body.sexoCadastral, diretorio: directory, googleSub: current.operational.googleSub, gmail: current.operational.gmail, emailVerificado: true, tipoDocumento: body.tipoDocumento, aceites: [{ ...body.aceites, aceito: true, aceitoEm: timestamp, googleSub: session.googleSub, ...requestMeta(request) }] }); const operational = update(current.operational, { states: { ...current.operational.states, cadastro: 'aguardando_analise', identidade: 'enviada' }, diretorio: directory, contato: contact(body), endereco: body.endereco }, timestamp); try { await storage.put(idKey(session.clienteId), identity, { createOnly: true }); await storage.put(opKey(session.clienteId), operational); } catch (error) { await storage.delete(`sistema/cpf/${cpfHash}.json`); throw error; } await auditar(storage, { clienteId: session.clienteId, acao: 'cadastro_enviado', ator: session.googleSub, papel: session.role, revision: operational.revision }, now); return operational;
}
export async function updateContact(storage, session, body, now = new Date()) { exact(body, ['revision', 'telefone', 'whatsapp', 'telefoneWhatsapp', 'endereco']); const current = await loadClient(storage, session.clienteId); checkRevision(current.operational, body.revision); validateAddress(body.endereco); const operational = update(current.operational, { contato: contact(body), endereco: body.endereco }, now.toISOString()); await storage.put(opKey(session.clienteId), operational); await auditar(storage, { clienteId: session.clienteId, acao: 'contato_endereco_alterado', ator: session.googleSub, papel: session.role, revision: operational.revision }, now); return operational;
}
export async function decide(storage, admin, clienteId, body, now = new Date()) { exact(body, ['revision', 'decisao', 'motivo']); if (!DECISIONS.has(body.decisao) || !textoSeguro(body.motivo, 1000)) throw httpError(422, 'DECISION_INVALID'); const current = await loadClient(storage, clienteId); checkRevision(current.operational, body.revision); const cadastro = body.decisao === 'reativado' ? 'aprovado' : body.decisao; const operational = update(current.operational, { states: { ...current.operational.states, cadastro } }, now.toISOString()); await storage.put(opKey(clienteId), operational); await auditar(storage, { clienteId, acao: body.decisao, ator: admin.googleSub, papel: admin.role, revision: operational.revision, motivo: body.motivo }, now); return operational;
}
export async function changeProtected(storage, admin, clienteId, body, now = new Date()) { exact(body, ['revision', 'motivo', 'changes']); if (!body.changes || !textoSeguro(body.motivo, 1000)) throw httpError(422, 'REASON_REQUIRED'); const current = await loadClient(storage, clienteId); checkRevision(current.identity, body.revision); const allowed = new Set(['nomeCivil', 'dataNascimento', 'nacionalidade', 'sexoCadastral', 'tipoDocumento']); for (const key of Object.keys(body.changes)) if (!allowed.has(key)) throw httpError(422, 'UNKNOWN_FIELD'); const before = structuredClone(current.identity); const identity = update(current.identity, body.changes, now.toISOString()); if (body.changes.sexoCadastral) identity.diretorio = diretorioParaSexo(body.changes.sexoCadastral); await storage.put(idKey(clienteId), identity); await auditar(storage, { clienteId, acao: 'dados_protegidos_corrigidos', ator: admin.googleSub, papel: admin.role, revision: identity.revision, motivo: body.motivo, metadados: { antes: redact(before), depois: redact(identity) } }, now); return identity;
}
export async function changePlan(storage, admin, clienteId, body, now = new Date()) { exact(body, ['revision', 'id', 'status', 'inicio', 'vencimento', 'limites', 'motivo']); const statuses = ['aguardando_ativacao', 'ativo', 'proximo_do_vencimento', 'vencido', 'suspenso', 'cancelado', 'cortesia']; if (!statuses.includes(body.status) || !textoSeguro(body.motivo, 1000)) throw httpError(422, 'PLAN_INVALID'); const current = await loadClient(storage, clienteId); checkRevision(current.operational, body.revision); const entry = { alteradoEm: now.toISOString(), autor: admin.googleSub, anterior: current.operational.plan, motivo: body.motivo }; const plan = { id: body.id, status: body.status, inicio: body.inicio, vencimento: body.vencimento, limites: body.limites, historico: [...current.operational.plan.historico, entry] }; const operational = update(current.operational, { plan }, now.toISOString()); await storage.put(opKey(clienteId), operational); await auditar(storage, { clienteId, acao: 'plano_alterado', ator: admin.googleSub, papel: admin.role, revision: operational.revision, motivo: body.motivo }, now); return operational;
}
export function publicSummary(client) { const o = client.operational; return { clienteId: o.clienteId, revision: o.revision, states: o.states, plan: o.plan, consumption: o.consumption, pendencias: o.pendencias, contato: o.contato, endereco: o.endereco, gmail: o.gmail, directory: o.diretorio, financeiro: { controle: 'manual', pagamentoOnline: false } }; }
export function adminView(client, now = new Date()) { return { ...client, idade: client.identity ? calcularIdade(client.identity.dataNascimento, now) : null, visualizacao: { somenteLeitura: true, identidadeAssumida: false } }; }
export function requireAdmin(session) { if (session.role !== 'SUPERADMIN') throw httpError(403, 'SUPERADMIN_REQUIRED'); }
export async function listClients(storage, query = {}) { const keys = await storage.list('clientes/'); const opKeys = keys.filter((key) => key.endsWith('/dados-privados/operacional.json')); const clients = await Promise.all(opKeys.map(async (key) => { const operational = await storage.get(key); const identity = await storage.get(idKey(operational.clienteId)); return { ...operational, nomeCivil: identity?.nomeCivil }; })); return clients.filter((c) => (!query.status || c.states.cadastro === query.status) && (!query.q || [c.clienteId, c.gmail, c.nomeCivil].some((v) => v?.toLowerCase().includes(query.q.toLowerCase())))); }
function base(clienteId, timestamp, data) { return { schemaVersion: 2, revision: 1, clienteId, criadoEm: timestamp, atualizadoEm: timestamp, ...data }; }
function update(current, changes, timestamp) { return { ...current, ...changes, revision: current.revision + 1, atualizadoEm: timestamp }; }
function checkRevision(current, revision) { if (!current || !Number.isInteger(revision) || revision !== current.revision) throw httpError(409, 'REVISION_CONFLICT'); }
function exact(value, fields) { if (!value || typeof value !== 'object' || Array.isArray(value)) throw httpError(400, 'BODY_INVALID'); for (const key of Object.keys(value)) if (!fields.includes(key)) throw httpError(422, 'UNKNOWN_FIELD'); for (const key of fields) if (!(key in value)) throw httpError(422, 'REQUIRED_FIELD'); }
function validateAcceptances(a) { for (const key of ['maioridade', 'veracidade', 'termos', 'privacidade', 'tratamentoDados', 'publicacaoFutura']) if (a?.[key] !== true) throw httpError(422, 'ACCEPTANCE_REQUIRED'); if (!a.versaoTermos || !a.versaoPrivacidade) throw httpError(422, 'ACCEPTANCE_VERSION_REQUIRED'); }
function validateAddress(a) { for (const key of ['cep', 'pais', 'estado', 'municipio', 'rua', 'numero', 'bairro']) textoSeguro(a?.[key], 160); }
function contact(body) { return { telefone: textoSeguro(body.telefone, 30), whatsapp: textoSeguro(body.whatsapp, 30), telefoneWhatsapp: Boolean(body.telefoneWhatsapp) }; }
function requestMeta(request) { return { ip: request.headers.get('cf-connecting-ip') || null, userAgent: request.headers.get('user-agent')?.slice(0, 300) || null }; }
function redact(value) { const copy = structuredClone(value); for (const key of ['cpf', 'dataNascimento', 'googleSub']) if (key in copy) copy[key] = '[PROTEGIDO]'; return copy; }
function adminSubs(env) { return new Set(String(env.SUPERADMIN_GOOGLE_SUBS || '').split(',').map((v) => v.trim()).filter(Boolean)); }
const opKey = (id) => privatePaths.dados(id,'operacional.json');
const idKey = (id) => privatePaths.dados(id,'identidade.json');
const docKey = (id) => privatePaths.documento(id,'manifesto.json');
const noticeKey = (id) => privatePaths.dados(id,'avisos.json');
