import { privatePaths } from './paths.js';
import messages from '../config/mensagens.json' with { type:'json' };
import plans from '../config/planos.json' with { type:'json' };
import { calcularIdade } from './validacao.js';
import { flags } from './publicacao.js';

export function brasilParts(now=new Date()){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(now);return Object.fromEntries(parts.filter(x=>x.type!=='literal').map(x=>[x.type,x.value]));}
export async function processBirthdays(storage,clients,now=new Date()){const d=brasilParts(now),out=[];const template=messages.modelos.find(x=>x.id==='aniversario-privado');for(const c of clients){if(!c.identity?.dataNascimento)continue;const [,m,day]=c.identity.dataNascimento.split('-');if(m!==d.month||day!==d.day)continue;const channel='aviso-privado',key=privatePaths.dados(c.operational.clienteId,`aniversarios/${d.year}-${channel}.json`);if(await storage.get(key))continue;const nome=c.draft?.perfil?.nomeArtistico||c.identity.nomeCivil;const record={clienteId:c.operational.clienteId,ano:Number(d.year),canal:channel,modeloId:template.id,modeloVersao:template.versao,mensagem:template.texto.replace('{nomeArtistico}',nome),whatsappUrl:c.consentWhatsapp?`https://wa.me/${c.operational.contato.whatsapp}?text=${encodeURIComponent(template.texto.replace('{nomeArtistico}',nome))}`:null,email:{preparado:true,enviadoAutomaticamente:false},enviado:false};await storage.put(key,record,{createOnly:true});out.push(record);}return out;}
export async function processAges(storage,clients,now=new Date()){const changed=[];for(const c of clients){if(!c.identity?.dataNascimento)continue;const age=calcularIdade(c.identity.dataNascimento,now),key=privatePaths.dados(c.operational.clienteId,'idade.json'),old=await storage.get(key);const next={idade:age,proximaAtualizacao:nextBirthday(c.identity.dataNascimento,now)};if(old?.idade!==age){await storage.put(key,next);changed.push({...next,clienteId:c.operational.clienteId,suspender:age<18});}}return changed;}
export async function processPlans(storage,clients,now=new Date()){const output=[];for(const c of clients){const plan=c.operational.plan,status=plan?.status;if(!['ativo','proximo_do_vencimento','vencido','suspenso','cortesia','cancelado'].includes(status))continue;const configured=plans.planos.find(x=>x.id===plan.id);const pending=!configured?.habilitado||configured?.limites?.status==='pendente';const item={clienteId:c.operational.clienteId,status,vencimento:plan.vencimento,acaoAutomatica:false,pendenciaAdministrativa:pending?'REGRA_COMERCIAL_PENDENTE':null};await storage.put(privatePaths.dados(c.operational.clienteId,'vencimento.json'),item);output.push(item);}return output;}
export async function reconcile(storage,handler,{prefix='sistema/operacional/clientes/',batchSize=50,checkpointKey='sistema/cron/reconciliacao.json'}={}){const keys=(await storage.list(prefix)).sort(),cp=await storage.get(checkpointKey),start=cp?.next||0,batch=keys.slice(start,start+batchSize);for(let i=0;i<batch.length;i++){await handler(batch[i]);await storage.put(checkpointKey,{next:start+i+1,total:keys.length});}if(start+batch.length>=keys.length)await storage.put(checkpointKey,{next:0,total:keys.length,completed:true});return {processed:batch.length,next:start+batch.length>=keys.length?0:start+batch.length};}
export async function auditPublic(publicStore){const issues=[];for(const key of await publicStore.list('')){const value=await publicStore.get(key);const raw=JSON.stringify(value);if(/dataNascimento|cpf|googleSub|nomeCivil|gmail|documentos/i.test(raw))issues.push({key,type:'PRIVATE_DATA'});if(key.includes('shards/')&&value?.anuncios?.some(x=>x.diretorio!==value.diretorio))issues.push({key,type:'MIXED_DIRECTORY'});}return issues;}
export async function executarCron(env,controller={}){if(!flags(env).cron)return {enabled:false,processed:0};return controller.run?controller.run():{enabled:true,processed:0};}
function nextBirthday(birth,now){const d=brasilParts(now),[,m,day]=birth.split('-');let y=Number(d.year);if(`${m}-${day}`<=`${d.month}-${d.day}`)y++;return `${y}-${m}-${day}`;}
