import { calcularIdade } from './validacao.js';
import { loadClient } from './clientes.js';
import { getDraft } from './rascunhos.js';
import { manifest as loadMedia } from './uploads.js';
import { sha256, validateKey } from './storage.js';
import categoriesConfig from '../config/categorias.json' with { type: 'json' };
import { assertClientMediaKey, privatePaths, publicPaths } from './paths.js';

export const DIRECTORIES = Object.freeze(['mulheres', 'homens', 'transex']);
export const RESERVED_SLUGS = new Set(['www','api','public','admin','painel','app','mail','cdn','suporte']);
const PUBLIC_FIELDS = ['schemaVersion','publicationId','clienteId','slug','nomeArtistico','idade','diretorio','cidadePrincipal','cidadesAtendimento','categorias','bairroPublico','apresentacao','caracteristicas','servicos','disponibilidade','contatoPublico','midiasManifesto'];

export function flags(env = {}) { return { publication: env.PUBLICATION_ENABLED === 'true', writes: env.PUBLIC_R2_WRITES_ENABLED === 'true', cron: env.CRON_ENABLED === 'true', publicV2: env.PUBLIC_V2_ENABLED === 'true' }; }
export function normalizeSlug(value) { const slug=String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,63); if(!slug||RESERVED_SLUGS.has(slug)) throw code('SLUG_INVALID'); return slug; }
export function canonicalPath(profile) { return `/${profile.cidadePrincipal}/${profile.diretorio}/${profile.categorias[0] || 'categoria'}/${profile.slug}`; }
export function projectPublic({ client, draft, media, now = new Date(), publicationId }) {
  const errors=[]; const o=client.operational, identity=client.identity, p=draft.perfil, s=draft.site;
  if(o.states?.cadastro!=='aprovado')errors.push('CADASTRO_NOT_APPROVED');
  if(!['aprovada','aprovado'].includes(o.states?.identidade))errors.push('IDENTITY_NOT_APPROVED');
  if(!['aprovados','aprovado'].includes(o.states?.documentos))errors.push('DOCUMENTS_NOT_APPROVED');
  if(o.states?.conta!=='ativa')errors.push('ACCOUNT_INACTIVE');
  if(!['ativo','cortesia'].includes(o.plan?.status))errors.push('PLAN_NOT_ALLOWED');
  if(p?.estado!=='validado'||s?.estado!=='validado')errors.push('DRAFT_INCOMPLETE');
  if(!identity?.dataNascimento||calcularIdade(identity.dataNascimento,now)<18)errors.push('MINOR_NOT_ALLOWED');
  if(!DIRECTORIES.includes(o.diretorio))errors.push('DIRECTORY_INVALID');
  if(p?.cidadePrincipal!=='londrina'||p?.cidadesAtendimento?.length!==1||p.cidadesAtendimento[0]!=='londrina')errors.push('CITY_INVALID');
  const allowed=categoriesConfig.porDiretorio[o.diretorio]||[]; if(!Array.isArray(p?.categorias)||p.categorias.some(x=>!allowed.includes(x)))errors.push('CATEGORY_INVALID');
  const validMedia=media?.itens?.filter(x=>!x.excluidaEm); if(!validMedia?.length||validMedia.some(x=>x.status!=='aprovada'))errors.push('MEDIA_INVALID');
  if(!p?.nomeArtistico||!p?.apresentacao)errors.push('REQUIRED_FIELD'); if(errors.length)throw code('PUBLICATION_INELIGIBLE',{details:errors});
  validMedia.forEach((item)=>assertMediaItem(item,o.clienteId));
  const slug=normalizeSlug(p.nomeArtistico); const projected={schemaVersion:2,publicationId,clienteId:o.clienteId,slug,nomeArtistico:p.nomeArtistico,idade:calcularIdade(identity.dataNascimento,now),diretorio:o.diretorio,cidadePrincipal:p.cidadePrincipal,cidadesAtendimento:p.cidadesAtendimento,categorias:p.categorias,bairroPublico:p.bairroPublico||null,apresentacao:p.apresentacao,caracteristicas:p.caracteristicas||{},servicos:p.servicos||[],disponibilidade:p.disponibilidade||{},contatoPublico:p.contatoPublico||{tipo:'nenhum',numero:null,consentimento:false},midiasManifesto:publicPaths.dados(o.clienteId,'midias.json')};
  const profile=Object.fromEntries(PUBLIC_FIELDS.map(k=>[k,projected[k]])); const category=p.categorias[0]||'categoria';
  return {profile,site:{schemaVersion:2,publicationId,clienteId:o.clienteId,canonicalPath:canonicalPath(profile),perfilPath:publicPaths.dados(o.clienteId,'perfil.json'),cidade:p.cidadePrincipal,diretorio:o.diretorio,categoria:category,slug,...pick(s,['titulo','descricao','urlExterna','corDestaque'])},media:{schemaVersion:2,publicationId,clienteId:o.clienteId,itens:validMedia.map((item)=>publicMedia(item,o.clienteId))}};
}
function publicMedia(x,clienteId){const folder=x.tipo==='foto'?'fotos':x.tipo==='video'?'videos':'audios';const output=pick(x,['id','tipo','largura','altura','duracao','principal','ordem']);output.arquivo=publicPaths.midia(clienteId,folder,x.arquivo.split('/').at(-1));for(const derivative of ['miniatura','capa'])if(x[derivative])output[derivative]={...x[derivative],arquivo:publicPaths.midia(clienteId,folder,x[derivative].arquivo.split('/').at(-1))};return output;}
function assertMediaItem(item,clienteId){assertClientMediaKey(item.arquivo,clienteId);for(const field of ['miniatura','capa'])if(item[field]?.arquivo)assertClientMediaKey(item[field].arquivo,clienteId);}
function pick(o,keys){return Object.fromEntries(keys.filter(k=>o?.[k]!==undefined).map(k=>[k,o[k]]));}
export function cardOf(p){return pick({...p,urlCanonica:canonicalPath(p),resumo:p.apresentacao.slice(0,180),miniaturaPrincipal:null},['clienteId','slug','nomeArtistico','idade','cidadePrincipal','diretorio','categorias','bairroPublico','miniaturaPrincipal','resumo','urlCanonica']);}
export async function buildShards(cards,{publicationId,target=100,maxBytes=256000,cidade,diretorio,categoria='todos'}={}){const sorted=[...cards].sort((a,b)=>a.slug.localeCompare(b.slug)||a.clienteId.localeCompare(b.clienteId));const chunks=[];let current=[];for(const card of sorted){const candidate=[...current,card];if(current.length&&(current.length>=target||JSON.stringify(candidate).length>maxBytes)){chunks.push(current);current=[];}current.push(card);}if(current.length)chunks.push(current);const shards=[];for(let i=0;i<chunks.length;i++){const body={schemaVersion:2,publicationId,cidade,diretorio,categoria,shard:String(i+1).padStart(3,'0'),totalShards:chunks.length,anuncios:chunks[i]};shards.push({...body,hash:await sha256(stable(body))});}return {manifest:{schemaVersion:2,publicationId,cidade,diretorio,categoria,quantidade:sorted.length,hash:await sha256(stable(shards)),shards:shards.map(x=>({id:x.shard,arquivo:`${x.shard}.json`,quantidade:x.anuncios.length,hash:x.hash}))},shards};}
export async function publishClient(privateStore,publicStore,clienteId,env={},options={}){const f=flags(env);if(!f.publication||!f.writes)throw code('PUBLICATION_DISABLED');const idem=options.idempotencyKey;if(!idem)throw code('IDEMPOTENCY_REQUIRED');const previous=await publicStore.get('dados/sistema/versao.json');const idemKey=privatePaths.dados(clienteId,`publicacao/idempotencia/${idem}.json`);const done=await privateStore.get(idemKey);if(done)return done;const publicationId=options.publicationId||`pub_${Date.now()}_${clienteId}`;try{const source=await loadMedia(privateStore,clienteId);const projection=projectPublic({client:await loadClient(privateStore,clienteId),draft:await getDraft(privateStore,clienteId),media:source,now:options.now,publicationId});await ensureSlug(publicStore,projection.profile);await promoteMedia(privateStore,publicStore,clienteId,source.itens.filter(x=>!x.excluidaEm));await putChanged(publicStore,publicPaths.dados(clienteId,'perfil.json'),projection.profile);await putChanged(publicStore,publicPaths.site(clienteId,'configuracao.json'),projection.site);await putChanged(publicStore,publicPaths.dados(clienteId,'midias.json'),projection.media);if(options.failBeforePointer)throw code('SIMULATED_FAILURE');const pointer={schemaVersion:2,publicationId,previousPublicationId:previous?.publicationId||null,activatedAt:(options.now||new Date()).toISOString()};await publicStore.put('dados/sistema/versao.json',pointer);const result={status:'publicada',clienteId,publicationId,canonicalPath:projection.site.canonicalPath};await privateStore.put(idemKey,result,{createOnly:true});await privateStore.put(privatePaths.dados(clienteId,'publicacao/status.json'),result);return result;}catch(error){await privateStore.put(privatePaths.dados(clienteId,`publicacao/tarefas/${publicationId}.json`),{publicationId,clienteId,status:'incompleta',erro:error.code||error.message,reprocessar:true});throw error;}}
async function promoteMedia(privateStore,publicStore,clienteId,items){for(const item of items){for(const source of [item.arquivo,item.miniatura?.arquivo,item.capa?.arquivo].filter(Boolean)){assertClientMediaKey(source,clienteId);const bytes=await privateStore.getBytes(source);if(!bytes)throw code('MEDIA_SOURCE_MISSING');const relative=source.slice(`clientes/${clienteId}/midias/`.length);const target=assertClientMediaKey(`clientes/${clienteId}/midias/${relative}`,clienteId);await publicStore.putBytes(target,bytes,mimeFor(target));}}}
function mimeFor(key){return key.endsWith('.webp')?'image/webp':key.endsWith('.mp4')?'video/mp4':'audio/mp4';}
async function ensureSlug(store,p){const key=`dados/sistema/slugs/${p.slug}.json`;validateKey(key);const old=await store.get(key);if(old&&old.clienteId!==p.clienteId)throw code('SLUG_COLLISION');await store.put(key,{slug:p.slug,clienteId:p.clienteId,urlCanonica:canonicalPath(p)});}
async function putChanged(store,key,value){const old=await store.get(key);if(stable(old)!==stable(value))await store.put(key,value);}
export async function rollback(publicStore,publicationId){const current=await publicStore.get('dados/sistema/versao.json');await publicStore.put('dados/sistema/versao.json',{...current,publicationId,previousPublicationId:current?.publicationId||null,rolledBackAt:new Date().toISOString()});return {publicationId,status:'rollback'};}
function stable(v){if(v===null||typeof v!=='object')return JSON.stringify(v);if(Array.isArray(v))return `[${v.map(stable).join(',')}]`;return `{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${stable(v[k])}`).join(',')}}`;}
function code(message,extra={}){return Object.assign(new Error(message),{code:message,status:422,...extra});}
