import { auditar } from './auditoria.js';
import { loadClient } from './clientes.js';
import { httpError } from './auth/session.js';
import { sha256 } from './storage.js';
import { assertClientMediaKey, privatePaths } from './paths.js';

const TYPES = { foto: { mime: 'image/webp', ext: 'webp', max: 12_000_000 }, miniatura: { mime: 'image/webp', ext: 'webp', max: 2_000_000 }, capa: { mime: 'image/webp', ext: 'webp', max: 2_000_000 }, video: { mime: 'video/mp4', ext: 'mp4', max: 80_000_000 }, audio: { mime: 'audio/mp4', ext: 'm4a', max: 20_000_000 } };
const TTL = 10 * 60_000;
export async function manifest(storage, clienteId) { return await storage.get(manifestKey(clienteId)) || { schemaVersion: 2, revision: 0, clienteId, proximoId: 1, itens: [], orfaos: [] }; }
export async function reserve(storage, session, input, now = new Date()) { await rateLimit(storage, session, now); exact(input, ['tipo','tamanho','hash','largura','altura','duracao','fps','midiaId']); const spec = TYPES[input.tipo]; if (!spec || !Number.isInteger(input.tamanho) || input.tamanho <= 0 || input.tamanho > spec.max || !/^[a-f0-9]{64}$/.test(input.hash)) throw httpError(422, 'UPLOAD_INVALID'); const client = await loadClient(storage, session.clienteId); const m = await manifest(storage, session.clienteId); enforcePlan(client.operational.plan, m, input.tipo); const derivative = ['miniatura','capa'].includes(input.tipo); if (derivative && !m.itens.some((x) => x.id === input.midiaId && (input.tipo === 'miniatura' ? x.tipo === 'foto' : x.tipo === 'video'))) throw httpError(422, 'MEDIA_PARENT_INVALID'); const id = derivative ? input.midiaId : String(m.proximoId).padStart(3, '0'); const uploadId = crypto.randomUUID(); const file = input.tipo === 'miniatura' ? `${id}-thumb.webp` : input.tipo === 'capa' ? `${id}-capa.webp` : `${id}.${spec.ext}`; const key = privatePaths.upload(session.clienteId, uploadId, file); assertClientMediaKey(key,session.clienteId); const reservation = { schemaVersion: 2, uploadId, clienteId: session.clienteId, midiaId: id, tipo: input.tipo, key, mime: spec.mime, tamanho: input.tamanho, hash: input.hash, largura: input.largura || null, altura: input.altura || null, duracao: input.duracao || null, fps: input.fps || null, status: 'reservado', criadoEm: now.toISOString(), expiraEm: new Date(now.getTime() + TTL).toISOString() }; await storage.put(reserveKey(session.clienteId, uploadId), reservation, { createOnly: true }); await auditar(storage, event(session, 'upload_reservado', m.revision, { uploadId, tipo: input.tipo }), now); return { uploadId, midiaId: id, metodo: 'PUT', uploadUrl: `/api/painel/uploads/${uploadId}/conteudo`, expiraEm: reservation.expiraEm, fallback: 'streaming-worker-privado' }; }
export async function receive(storage, session, uploadId, request, now = new Date()) { const r = await reservation(storage, session, uploadId, now); if (!['reservado','enviando'].includes(r.status)) throw httpError(409, 'UPLOAD_STATE_INVALID'); const length = Number(request.headers.get('content-length') || 0); if (length !== r.tamanho || request.headers.get('content-type') !== r.mime) throw httpError(422, 'UPLOAD_SIZE_OR_TYPE_MISMATCH'); const bytes = new Uint8Array(await request.arrayBuffer()); if (bytes.length !== r.tamanho || !signature(bytes, r.tipo)) throw httpError(422, 'FILE_SIGNATURE_INVALID'); await storage.putBytes(r.key, bytes, r.mime); r.status = 'recebido'; r.recebidoEm = now.toISOString(); await storage.put(reserveKey(session.clienteId, uploadId), r); await auditar(storage, event(session, 'upload_recebido', 0, { uploadId }), now); return { uploadId, status: r.status }; }
export async function finish(storage, session, uploadId, now = new Date()) { const r = await reservation(storage, session, uploadId, now, true); if (r.status === 'finalizado') return r.resultado; if (r.status !== 'recebido') throw httpError(409, 'UPLOAD_NOT_RECEIVED'); const bytes = await storage.getBytes(r.key); r.status = 'validando'; await storage.put(reserveKey(session.clienteId, uploadId), r); if (!bytes || await sha256(bytes) !== r.hash || !signature(bytes, r.tipo)) { r.status = 'rejeitado'; await storage.put(reserveKey(session.clienteId, uploadId), r); throw httpError(422, 'UPLOAD_HASH_INVALID'); } const client = await loadClient(storage, session.clienteId); const m = await manifest(storage, session.clienteId); enforcePlan(client.operational.plan, m, r.tipo); if (m.itens.some((x) => x.uploadId === uploadId)) return m.itens.find((x) => x.uploadId === uploadId); const folder = r.tipo === 'video' || r.tipo === 'capa' ? 'videos' : r.tipo === 'audio' ? 'audios' : 'fotos'; const finalKey = privatePaths.midia(session.clienteId,folder,r.key.split('/').at(-1)); assertClientMediaKey(finalKey,session.clienteId); await storage.putBytes(finalKey, bytes, r.mime); let item; if (['miniatura','capa'].includes(r.tipo)) { item = m.itens.find((x) => x.id === r.midiaId); item[r.tipo] = { arquivo: finalKey, hash: r.hash, tamanho: r.tamanho, dimensoes: r.largura ? { largura: r.largura, altura: r.altura } : null }; } else { item = { id: r.midiaId, uploadId, tipo: r.tipo, arquivo: finalKey, ordem: m.itens.length + 1, principal: r.tipo === 'foto' && !m.itens.some((x) => x.tipo === 'foto' && x.principal), status: 'pendente', hash: r.hash, dimensoes: r.largura ? { largura: r.largura, altura: r.altura } : null, tamanho: r.tamanho, duracao: r.duracao, fps: r.fps, criadoEm: now.toISOString() }; m.itens.push(item); m.proximoId = Math.max(m.proximoId, Number(r.midiaId) + 1); } m.revision++; await storage.put(manifestKey(session.clienteId), m); r.status = 'finalizado'; r.resultado = item; await storage.put(reserveKey(session.clienteId, uploadId), r); await auditar(storage, event(session, 'upload_finalizado', m.revision, { uploadId, midiaId: item.id }), now); return item; }
export async function cancel(storage, session, uploadId, now = new Date()) { const r = await reservation(storage, session, uploadId, now, true); if (r.status === 'finalizado') throw httpError(409, 'UPLOAD_ALREADY_FINALIZED'); r.status = 'expirado'; await storage.put(reserveKey(session.clienteId, uploadId), r); await auditar(storage, event(session, 'upload_cancelado', 0, { uploadId }), now); return { uploadId, status: r.status }; }
export async function reorder(storage, session, input, now = new Date()) { exact(input, ['revision','ids']); const m = await manifest(storage, session.clienteId); checkRevision(m, input.revision); if (!Array.isArray(input.ids) || input.ids.length !== m.itens.length || new Set(input.ids).size !== m.itens.length || input.ids.some((id) => !m.itens.some((x) => x.id === id))) throw httpError(422, 'MEDIA_ORDER_INVALID'); m.itens.sort((a,b) => input.ids.indexOf(a.id)-input.ids.indexOf(b.id)).forEach((x,i)=>x.ordem=i+1); return saveManifest(storage, session, m, 'midias_reordenadas', now); }
export async function principal(storage, session, id, input, now = new Date()) { exact(input, ['revision']); const m = await manifest(storage, session.clienteId); checkRevision(m, input.revision); const item = m.itens.find((x)=>x.id===id && x.tipo==='foto'); if (!item) throw httpError(404,'MEDIA_NOT_FOUND'); m.itens.forEach((x)=>{if(x.tipo==='foto')x.principal=x.id===id}); return saveManifest(storage,session,m,'foto_principal_alterada',now); }
export async function remove(storage, session, id, input, now = new Date()) { exact(input, ['revision']); const m = await manifest(storage, session.clienteId); checkRevision(m,input.revision); const index=m.itens.findIndex((x)=>x.id===id); if(index<0)throw httpError(404,'MEDIA_NOT_FOUND'); const [item]=m.itens.splice(index,1); m.orfaos.push({...item,recuperavelAte:new Date(now.getTime()+7*864e5).toISOString()}); m.itens.forEach((x,i)=>x.ordem=i+1); if(item.principal){const first=m.itens.find((x)=>x.tipo==='foto');if(first)first.principal=true} return saveManifest(storage,session,m,'midia_excluida',now); }
export async function moderate(storage, admin, clienteId, id, input, now=new Date()){exact(input,['revision','decisao','observacao','solicitarSubstituicao']);if(!['pendente','aprovada','rejeitada'].includes(input.decisao))throw httpError(422,'MEDIA_DECISION_INVALID');const m=await manifest(storage,clienteId);checkRevision(m,input.revision);const item=m.itens.find((x)=>x.id===id);if(!item)throw httpError(404,'MEDIA_NOT_FOUND');item.status=input.decisao;item.moderacao={observacao:String(input.observacao||'').slice(0,1000),solicitarSubstituicao:Boolean(input.solicitarSubstituicao),em:now.toISOString()};m.revision++;await storage.put(manifestKey(clienteId),m);await auditar(storage,{clienteId,acao:'midia_decidida',ator:admin.googleSub,papel:admin.role,revision:m.revision,metadados:{midiaId:id,decisao:input.decisao}},now);return m}
function enforcePlan(plan,m,type){if(['miniatura','capa'].includes(type))return;const bucket=type==='foto'||type==='miniatura'?'fotos':type==='video'||type==='capa'?'videos':'audios';const limit=plan?.limites?.[bucket];if(!Number.isInteger(limit))throw httpError(403,'PLAN_LIMIT_PENDING');const count=m.itens.filter((x)=>bucket==='fotos'?x.tipo==='foto':bucket==='videos'?x.tipo==='video':x.tipo==='audio').length;if(count>=limit)throw httpError(403,'PLAN_LIMIT_EXCEEDED')}
function signature(b,type){if(['foto','miniatura','capa'].includes(type))return b.length>=12&&new TextDecoder().decode(b.slice(0,4))==='RIFF'&&new TextDecoder().decode(b.slice(8,12))==='WEBP';if(['video','audio'].includes(type))return b.length>=12&&new TextDecoder().decode(b.slice(4,8))==='ftyp';return false}
async function reservation(storage,session,id,now,allowExpired=false){if(!/^[0-9a-f-]{36}$/.test(id))throw httpError(422,'UPLOAD_ID_INVALID');const r=await storage.get(reserveKey(session.clienteId,id));if(!r||r.clienteId!==session.clienteId)throw httpError(404,'UPLOAD_NOT_FOUND');if(!allowExpired&&new Date(r.expiraEm)<=now){r.status='expirado';await storage.put(reserveKey(session.clienteId,id),r);throw httpError(410,'UPLOAD_EXPIRED')}return r}
async function saveManifest(storage,session,m,acao,now){m.revision++;await storage.put(manifestKey(session.clienteId),m);await auditar(storage,event(session,acao,m.revision),now);return m}
function checkRevision(m,r){if(!Number.isInteger(r)||m.revision!==r)throw httpError(409,'REVISION_CONFLICT')}
function exact(v,fields){if(!v||typeof v!=='object'||Array.isArray(v))throw httpError(400,'BODY_INVALID');for(const k of Object.keys(v))if(!fields.includes(k))throw httpError(422,'UNKNOWN_FIELD')}
function event(s,acao,revision,metadados={}){return{clienteId:s.clienteId,acao,ator:s.googleSub,papel:s.role,revision,metadados}}
async function rateLimit(storage,session,now){const window=Math.floor(now.getTime()/60000),key=`sistema/rate-limit/uploads/${session.clienteId}/${window}.json`,record=await storage.get(key)||{count:0};if(record.count>=30){await auditar(storage,event(session,'limite_upload_tentado',0),now);throw httpError(429,'RATE_LIMITED')}record.count++;await storage.put(key,record)}
const reserveKey=(id,u)=>privatePaths.upload(id,u,'reserva.json');export const manifestKey=(id)=>privatePaths.rascunho(id,'midias.json');
