import assert from 'node:assert/strict';
import test from 'node:test';
import { BLOGGER_LIMITS, BloggerError, parseBloggerFeed, sanitizePostHtml, syncBlogger, validateBloggerUrl } from '../../business/blogger.js';
import { minisiteDocument } from '../../frontend/minisite/template.js';
import { normalizeProfileProjection } from '../../business/publishing.js';

const xml = (entries = '') => `<?xml version="1.0"?><feed xmlns="http://www.w3.org/2005/Atom"><generator>Blogger</generator>${entries}</feed>`;
const entry = `<entry><id>post-1</id><title>Olá</title><published>2026-08-14T00:00:00Z</published><updated>invalid</updated><link rel="alternate" href="https://demo.blogspot.com/p/ola.html"/><summary>&lt;p&gt;Resumo&lt;/p&gt;</summary><content type="html">&lt;p onclick="bad()"&gt;Permitido &lt;strong&gt;forte&lt;/strong&gt;&lt;script&gt;bad()&lt;/script&gt;&lt;img src="x" onerror="bad()"&gt;&lt;a href="javascript:bad()"&gt;x&lt;/a&gt;&lt;iframe src="https://evil.test"&gt;&lt;/iframe&gt;&lt;form&gt;x&lt;/form&gt;&lt;object&gt;x&lt;/object&gt;&lt;embed src="x"&gt;</content></entry>`;

for (const value of ['http://demo.blogspot.com','https://localhost','https://127.0.0.1','https://[::1]','https://10.1.2.3','https://172.20.1.2','https://192.168.1.1','https://169.254.1.1','https://user:pass@demo.blogspot.com']) test(`rejects unsafe Blogger URL ${value}`,()=>assert.throws(()=>validateBloggerUrl(value),BloggerError));
test('accepts safe blogspot and custom HTTPS URLs',()=>{assert.equal(validateBloggerUrl('https://demo.blogspot.com/'),'https://demo.blogspot.com');assert.equal(validateBloggerUrl('https://blog.example/'),'https://blog.example')});
test('sanitizes hostile HTML while retaining the small allowlist',()=>{const value=sanitizePostHtml('<p onclick="x()">ok<strong>yes</strong><script>x</script><iframe></iframe><form>x</form><object>x</object><embed><a href="javascript:x()">bad</a><a href="https://safe.test">safe</a><img src=x onerror=x>');assert.match(value,/<strong>yes<\/strong>/);for(const bad of ['script','onclick','iframe','form','object','embed','javascript:','onerror','src="x"'])assert.equal(value.includes(bad),false);assert.match(value,/rel="noopener noreferrer"/)});
test('parses Blogger Atom, deduplicates posts, handles invalid dates and partial content',()=>{const blog=parseBloggerFeed(xml(entry+entry+'<entry><id>partial</id></entry>'),'https://demo.blogspot.com');assert.equal(blog.posts.length,1);assert.equal(blog.posts[0].updatedAt,null);assert.doesNotMatch(blog.posts[0].content,/script|onclick|iframe|form|javascript:/)});
test('rejects malformed/non-Blogger feeds and permits an empty Blogger feed',()=>{assert.throws(()=>parseBloggerFeed('<rss/>','https://custom.example'),{code:'NOT_BLOGGER'});assert.deepEqual(parseBloggerFeed(xml(),'https://demo.blogspot.com').posts,[])});
test('sync uses limited Atom endpoint and accepts custom domain only with Blogger proof',async()=>{let called;const fetcher=async(url)=>{called=String(url);return new Response(xml(entry),{headers:{'content-type':'application/atom+xml'}})};const blog=await syncBlogger({url:'https://custom.example',fetcher});assert.match(called,/feeds\/posts\/default\?alt=atom&max-results=10/);assert.equal(blog.posts.length,1)});
test('sync rejects redirects to private destinations',async()=>{await assert.rejects(syncBlogger({url:'https://demo.blogspot.com',fetcher:async()=>new Response(null,{status:302,headers:{location:'https://127.0.0.1/feed'}})}),{code:'INVALID_URL'})});
for(const status of [404,500])test(`sync reports HTTP ${status}`,async()=>assert.rejects(syncBlogger({url:'https://demo.blogspot.com',fetcher:async()=>new Response('',{status})}),{code:`HTTP_${status}`}));
test('sync rejects oversized response',async()=>assert.rejects(syncBlogger({url:'https://demo.blogspot.com',fetcher:async()=>new Response('x'.repeat(BLOGGER_LIMITS.bytes+1))}),{code:'FEED_TOO_LARGE'}));
test('sync applies timeout',async()=>assert.rejects(syncBlogger({url:'https://demo.blogspot.com',timeoutMs:5,fetcher:async(_url,{signal})=>new Promise((_,reject)=>signal.addEventListener('abort',()=>reject(new DOMException('aborted','AbortError'))))}),{code:'TIMEOUT'}));
test('minisite hides empty blog and renders safe original post',()=>{assert.doesNotMatch(minisiteDocument({name:'Ana'},'ana'),/Publicações/);const html=minisiteDocument({name:'Ana',blog:parseBloggerFeed(xml(entry),'https://demo.blogspot.com')},'ana');assert.match(html,/Publicações/);assert.match(html,/Ver publicação original/);assert.doesNotMatch(html,/onclick|<script|<iframe|javascript:/)});
test('profile projection exposes only the client-side Blogger feed URL',()=>{const projection=normalizeProfileProjection({slug:'ana',name:'Ana',bloggerFeedUrl:'https://demo.blogspot.com',blog:{posts:[{secret:'no'}],token:'secret'}},'2026-08-14T00:00:00.000Z');assert.equal(projection.bloggerFeedUrl,'https://demo.blogspot.com');assert.equal('blog' in projection,false);assert.equal('token' in projection,false)});
