import { sha256 } from '../storage.js';
import { httpError } from './session.js';
export const GOOGLE_SCOPES = Object.freeze(['openid', 'email', 'profile']);
const ISSUERS = new Set(['https://accounts.google.com', 'accounts.google.com']);
export function googleConfigurado(env) { return Boolean(env.GOOGLE_CLIENT_ID && env.GOOGLE_CLIENT_SECRET && env.SESSION_SECRET && env.APP_ORIGIN); }
export async function iniciarGoogle(storage, env, now = new Date()) { if (!googleConfigurado(env)) throw httpError(503, 'GOOGLE_CONFIGURATION_PENDING'); const state = random(); const nonce = random(); const verifier = random(); const challenge = base64url(await crypto.subtle.digest('SHA-256', new TextEncoder().encode(verifier))); await storage.put(`sistema/oauth/${await sha256(state)}.json`, { state, nonce, verifier, exp: now.getTime() + 600000 }, { createOnly: true }); const redirectUri = `${env.APP_ORIGIN}/api/auth/google/callback`; const url = new URL('https://accounts.google.com/o/oauth2/v2/auth'); url.search = new URLSearchParams({ client_id: env.GOOGLE_CLIENT_ID, redirect_uri: redirectUri, response_type: 'code', scope: GOOGLE_SCOPES.join(' '), state, nonce, code_challenge: challenge, code_challenge_method: 'S256', prompt: 'select_account' }); return url.toString(); }
export async function concluirGoogle(storage, env, params, provider = defaultProvider, now = new Date()) { const state = params.get('state'); const code = params.get('code'); if (!state || !code) throw httpError(400, 'OAUTH_CALLBACK_INVALID'); const key = `sistema/oauth/${await sha256(state)}.json`; const transaction = await storage.get(key); await storage.delete(key); if (!transaction || transaction.state !== state || transaction.exp < now.getTime()) throw httpError(400, 'STATE_INVALID'); const idToken = await provider.exchange(code, transaction.verifier, env); const claims = await provider.verify(idToken, env.GOOGLE_CLIENT_ID, now); if (!ISSUERS.has(claims.iss)) throw httpError(401, 'TOKEN_ISSUER_INVALID'); if (claims.aud !== env.GOOGLE_CLIENT_ID) throw httpError(401, 'TOKEN_AUDIENCE_INVALID'); if (Number(claims.exp) * 1000 <= now.getTime()) throw httpError(401, 'TOKEN_EXPIRED'); if (claims.nonce !== transaction.nonce) throw httpError(401, 'NONCE_INVALID'); if (claims.email_verified !== true) throw httpError(403, 'EMAIL_NOT_VERIFIED'); const gmail = String(claims.email ?? '').toLowerCase(); if (!/^[^@\s]+@gmail\.com$/.test(gmail)) throw httpError(403, 'PERSONAL_GMAIL_REQUIRED'); if (!claims.sub) throw httpError(401, 'TOKEN_SUB_INVALID'); return { googleSub: String(claims.sub), gmail, nome: String(claims.name || '') };
}
export const defaultProvider = { async exchange(code, verifier, env) { const response = await fetch('https://oauth2.googleapis.com/token', { method: 'POST', headers: { 'content-type': 'application/x-www-form-urlencoded' }, body: new URLSearchParams({ code, client_id: env.GOOGLE_CLIENT_ID, client_secret: env.GOOGLE_CLIENT_SECRET, redirect_uri: `${env.APP_ORIGIN}/api/auth/google/callback`, grant_type: 'authorization_code', code_verifier: verifier }) }); if (!response.ok) throw httpError(401, 'TOKEN_EXCHANGE_FAILED'); return (await response.json()).id_token; }, async verify(token, audience, now) { const parts = token.split('.'); if (parts.length !== 3) throw httpError(401, 'TOKEN_INVALID'); const header = JSON.parse(atob(parts[0].replaceAll('-', '+').replaceAll('_', '/'))); const claims = JSON.parse(atob(parts[1].replaceAll('-', '+').replaceAll('_', '/'))); const jwks = await (await fetch('https://www.googleapis.com/oauth2/v3/certs')).json(); const jwk = jwks.keys.find((key) => key.kid === header.kid && key.alg === 'RS256'); if (!jwk) throw httpError(401, 'TOKEN_KEY_INVALID'); const key = await crypto.subtle.importKey('jwk', jwk, { name: 'RSASSA-PKCS1-v1_5', hash: 'SHA-256' }, false, ['verify']); const signature = Uint8Array.from(atob(parts[2].replaceAll('-', '+').replaceAll('_', '/')), (c) => c.charCodeAt(0)); const valid = await crypto.subtle.verify('RSASSA-PKCS1-v1_5', key, signature, new TextEncoder().encode(`${parts[0]}.${parts[1]}`)); if (!valid || claims.aud !== audience || Number(claims.exp) * 1000 <= now.getTime()) throw httpError(401, 'TOKEN_INVALID'); return claims; } };
function random() { return base64url(crypto.getRandomValues(new Uint8Array(32))); }
function base64url(value) { return btoa(String.fromCharCode(...new Uint8Array(value))).replaceAll('+', '-').replaceAll('/', '_').replaceAll('=', ''); }
