import { sha256 } from '../storage.js';
const COOKIE = '__Host-portal_session';
export async function criarSessao(storage, account, now = new Date()) { const raw = randomToken(); const id = await sha256(raw); const expiresAt = new Date(now.getTime() + 8 * 60 * 60 * 1000).toISOString(); const session = { schemaVersion: 2, id, clienteId: account.clienteId, googleSub: account.googleSub, role: account.role, csrf: randomToken(), criadoEm: now.toISOString(), atualizadoEm: now.toISOString(), expiresAt, authTime: now.toISOString(), revision: 1 }; await storage.put(`sistema/sessoes/${id}.json`, session, { createOnly: true }); return { session, cookie: `${COOKIE}=${raw}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=28800` }; }
export async function obterSessao(request, storage, now = new Date()) { const match = request.headers.get('cookie')?.match(new RegExp(`(?:^|; )${COOKIE}=([^;]+)`)); if (!match) return null; const id = await sha256(match[1]); const session = await storage.get(`sistema/sessoes/${id}.json`); if (!session || Date.parse(session.expiresAt) <= now.getTime()) return null; return session; }
export async function logout(request, storage) { const match = request.headers.get('cookie')?.match(new RegExp(`(?:^|; )${COOKIE}=([^;]+)`)); if (match) await storage.delete(`sistema/sessoes/${await sha256(match[1])}.json`); return `${COOKIE}=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0`; }
export async function logoutAll(storage, googleSub) { const keys = await storage.list('sistema/sessoes/'); for (const key of keys) { const session = await storage.get(key); if (session?.googleSub === googleSub) await storage.delete(key); } }
export function validarMutacao(request, session, origin) { if (!origin || request.headers.get('origin') !== origin) throw httpError(403, 'ORIGIN_INVALID'); if (request.headers.get('x-csrf-token') !== session.csrf) throw httpError(403, 'CSRF_INVALID'); }
export function exigirRecente(session, now = new Date()) { if (now.getTime() - Date.parse(session.authTime) > 15 * 60 * 1000) throw httpError(403, 'REAUTH_REQUIRED'); }
export function httpError(status, code) { return Object.assign(new Error(code), { status, code }); }
function randomToken() { const bytes = crypto.getRandomValues(new Uint8Array(32)); return btoa(String.fromCharCode(...bytes)).replaceAll('+', '-').replaceAll('/', '_').replaceAll('=', ''); }
